[workspace]
channels = ["conda-forge"]
name = "pixi-pytroch-example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
check-pytorch = "python scripts/verify_pytorch.py"

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.12.*"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
torchaudio = ">=2.7.1,<3"

[pypi-dependencies]
huggingface-hub = ">=0.34.1, <0.35"

# https://pixi.sh/latest/python/pytorch/#installing-from-conda-forge
[feature.gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "*"

[feature.cpu.dependencies]
pytorch-cpu = "*"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
default = ["gpu"]
